import { createClient } from '@supabase/supabase-js';

// Import auto-generated Supabase credentials from Make
// @ts-ignore - This file is auto-generated by Make
import { projectId, publicAnonKey } from '/utils/supabase/info';

// Construct Supabase URL from project ID
const supabaseUrl = `https://${projectId}.supabase.co`;
const supabaseAnonKey = publicAnonKey;

export const supabase = createClient(supabaseUrl, supabaseAnonKey);

// Database Types
export type Profile = {
  id: string;
  email: string;
  full_name: string;
  role: 'system_admin' | 'Clinic Admin' | 'Doctor' | 'Nurse/Vaccinator';
  phone: string | null;
  is_active: boolean;
  created_at: string;
  updated_at: string;
};

export type Patient = {
  id: string;
  full_name: string;
  age: number;
  sex: 'Male' | 'Female';
  address: string;
  barangay_id: string;
  contact_number: string;
  email: string | null;
  created_at: string;
  updated_at: string;
};

export type Incident = {
  id: string;
  patient_id: string;
  incident_date: string;
  incident_time: string | null;
  animal_type: 'Dog' | 'Cat' | 'Other';
  animal_description: string | null;
  bite_site: string;
  who_category: 'I' | 'II' | 'III';
  location_lat: number | null;
  location_lng: number | null;
  barangay_id: string;
  status: 'Active' | 'Completed' | 'Missed' | 'Lost to Follow-up';
  reported_by: string | null;
  created_at: string;
  updated_at: string;
};

export type PEPSchedule = {
  id: string;
  incident_id: string;
  dose_day: 0 | 3 | 7 | 14 | 28;
  scheduled_date: string;
  administered_date: string | null;
  vaccine_type: string;
  vaccine_lot_number: string | null;
  administered_by: string | null;
  status: 'Pending' | 'Upcoming' | 'Done' | 'Missed' | 'Skipped';
  notes: string | null;
  created_at: string;
  updated_at: string;
};

export type Inventory = {
  id: string;
  item_name: string;
  item_type: 'Vaccine' | 'Immunoglobulin' | 'Supply' | 'Medicine';
  current_stock: number;
  unit: string;
  reorder_level: number;
  expiry_date: string | null;
  last_updated: string;
  updated_by: string | null;
};

export type Animal = {
  id: string;
  animal_id: string;
  animal_type: 'Dog' | 'Cat' | 'Other';
  breed: string | null;
  owner_name: string;
  owner_contact: string | null;
  barangay_id: string;
  is_vaccinated: boolean;
  last_vaccination_date: string | null;
  next_vaccination_due: string | null;
  created_at: string;
  updated_at: string;
};

export type Notification = {
  id: string;
  incident_id: string | null;
  patient_id: string;
  notification_type: 'SMS' | 'Email' | 'Both';
  recipient: string;
  message: string;
  status: 'Pending' | 'Sent' | 'Failed' | 'Delivered';
  sent_at: string | null;
  delivery_status: string | null;
  created_at: string;
};

export type Barangay = {
  id: string;
  name: string;
  population: number | null;
  created_at: string;
};
